<?php

namespace gospelcenter\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('l');
        
        $qb->leftJoin('l.centers', 'c1');
        
        $qb->leftJoin('l.events', 'e');
        $qb->leftJoin('e.centers', 'c2');
        
        $qb->leftJoin('l.celebrations', 'cel');
        $qb->leftJoin('cel.center', 'c3');
        
        $qb->where('c1.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orWhere('c2.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orWhere('c3.ref = :center')
            ->setParameter('center', $center->getRef());
        
        return $qb->getQuery()->getResult();
    }
    
    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('l');
    
        
        return $qb;
    }
    
    public function findOne($location)
    {
        $qb = $this->createQueryBuilder('l');
        
        $qb->where('l.id = :location')
            ->setParameter('location', $location);
            
        return $qb->getQuery()->getArrayResult();
        
    }
}
