<?php

namespace gospelcenter\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{

    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->addSelect('p');

        $qb->join('s.page', 'p');
        $qb->join('p.language', 'l');
        $qb->join('p.center', 'c');
        
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->addOrderBy('p.title', 'ASC')
            ->addOrderBy('l.ref', 'ASC')
            ->addOrderBy('s.title', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('s');
        
        return $qb;
    }
    
    public function findAllGlobal()
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->join('s.page', 'p');
        $qb->join('p.language', 'l');
        
        
        $qb->addOrderBy('p.title', 'ASC')
            ->addOrderBy('l.ref', 'ASC')
            ->addOrderBy('s.title', 'ASC');
        
        $qb->andWhere('p.center IS NULL');
        
        return $qb->getQuery()->getResult();
    }
    
}
