parameters:
#    gospelcenter_people.example.class: gospelcenter\PUserBundle\Example

services:
    gospelcenter.group.form.type:
        class: gospelcenter\UserBundle\Form\Type\GroupWithRolesFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: gospelcenter_userbundle_groupwithrolesformtype }
