parameters:
#    gospelcenter_people.example.class: gospelcenter\PUserBundle\Example

services:
#    gospelcenter_user.example:
#        class: %gospelcenter_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
