gospelcenterAdminGlobal:
    resource: "@gospelcenterAdminBundle/Resources/config/routingGlobal.yml"
    prefix:   /admin

gospelcenterPageGlobal:
    resource: "@gospelcenterPageBundle/Resources/config/routingGlobal.yml"
    prefix:   /