###########################
########## PROD ###########
###########################

gospelcenterAPI:
    resource: "@gospelcenterAPIBundle/Resources/config/routing.yml"
    prefix:   /api

gospelcenterAdminGlobal:
    resource: "@gospelcenterAdminBundle/Resources/config/routingGlobal.yml"
    prefix:   /admin
    host: "gospel-center.org"

gospelcenterAdmin:
    resource: "@gospelcenterAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    host: "gc-{center}.org"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterEvents:
    resource: "@gospelcenterEventBundle/Resources/config/routing.yml"
    prefix:   /events
    host: "gc-{center}.org"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterAgenda:
    resource: "@gospelcenterEventBundle/Resources/config/routingAgenda.yml"
    prefix:   /agenda
    host: "gc-{center}.org"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterCelebrations:
    resource: "@gospelcenterCelebrationBundle/Resources/config/routing.yml"
    prefix:   /celebrations
    host: "gc-{center}.org"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterPage:
    resource: "@gospelcenterPageBundle/Resources/config/routing.yml"
    prefix:   /
    host: "gc-{center}.org"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterTV:
    resource: "@gospelcenterMediaBundle/Resources/config/routing.yml"
    prefix:   /
    host: "gospel-center.tv"

gospelcenterPageGlobal:
    resource: "@gospelcenterPageBundle/Resources/config/routingGlobal.yml"
    prefix:   /
    host: "gospel-center.org"


###########################
########### DEV ###########
###########################

#gospelcenterAPI:
#    resource: "@gospelcenterAPIBundle/Resources/config/routing.yml"
#    prefix:   /api
#
#gospelcenter_dev_AdminGlobal:
#    resource: "@gospelcenterAdminBundle/Resources/config/routingGlobal.yml"
#    prefix:   /admin
#
#gospelcenter_dev_Admin:
#    resource: "@gospelcenterAdminBundle/Resources/config/routing.yml"
#    prefix:   /{center}/admin
#    requirements:
#        center: lausanne|annecy|montreux|jura
#
#gospelcenter_dev_Events:
#    resource: "@gospelcenterEventBundle/Resources/config/routing.yml"
#    prefix:   /{center}/events
#    requirements:
#        center: lausanne|annecy|montreux|jura
#
#gospelcenter_dev_Agenda:
#    resource: "@gospelcenterEventBundle/Resources/config/routingAgenda.yml"
#    prefix:   /{center}/agenda
#    requirements:
#        center: lausanne|annecy|montreux|jura
#
#gospelcenter_dev_Celebrations:
#    resource: "@gospelcenterCelebrationBundle/Resources/config/routing.yml"
#    prefix:   /{center}/celebrations
#    requirements:
#        center: lausanne|annecy|montreux|jura
#
#gospelcenter_dev_Page:
#    resource: "@gospelcenterPageBundle/Resources/config/routing.yml"
#    prefix:   /{center}/
#    requirements:
#        center: lausanne|annecy|montreux|jura
#
#gospelcenter_dev_TV:
#    resource: "@gospelcenterMediaBundle/Resources/config/routing.yml"
#    prefix:   /tv
#
#gospelcenter_dev_PageGlobal:
#    resource: "@gospelcenterPageBundle/Resources/config/routingGlobal.yml"
#    prefix:   /
#