###########################   
########### API ###########
###########################
gospelcenterAPI:
    resource: "@gospelcenterAPIBundle/Resources/config/routing.yml"
    prefix:   /api

gospelcenterImage:
    resource: "@gospelcenterImageBundle/Resources/config/routing.yml"
    prefix:   /image

###########################   
########## PROD ###########
###########################

gospelcenterAdminGlobal:
    resource: "@gospelcenterAdminBundle/Resources/config/routingGlobal.yml"
    prefix:   /admin
    host: "gospelcenter.local"

gospelcenterAdmin:
    resource: "@gospelcenterAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    host: "{center}.gospelcenter.local"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterEvents:
    resource: "@gospelcenterEventBundle/Resources/config/routing.yml"
    prefix:   /events
    host: "{center}.gospelcenter.local"
    requirements:
        center: lausanne|annecy|montreux|jura
        
gospelcenterAgenda:
    resource: "@gospelcenterEventBundle/Resources/config/routingAgenda.yml"
    prefix:   /agenda
    host: "{center}.gospelcenter.local"
    requirements:
        center: lausanne|annecy|montreux|jura
        
gospelcenterCelebrations:
    resource: "@gospelcenterCelebrationBundle/Resources/config/routing.yml"
    prefix:   /celebrations
    host: "{center}.gospelcenter.local"
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterPage:
    resource: "@gospelcenterPageBundle/Resources/config/routing.yml"
    prefix:   /
    host: "{center}.gospelcenter.local"
    requirements:
        center: lausanne|annecy|montreux|jura
        
gospelcenterPageGlobal:
    resource: "@gospelcenterPageBundle/Resources/config/routingGlobal.yml"
    prefix:   /
    host: "gospelcenter.local"

gospelcenterTV:
    resource: "@gospelcenterMediaBundle/Resources/config/routing.yml"
    prefix:   /
    host: "tv.gospelcenter.local"

###########################   
########### DEV ###########
###########################

gospelcenterAdminGlobal_dev:
    resource: "@gospelcenterAdminBundle/Resources/config/routingGlobal.yml"
    prefix:   /admin

gospelcenterTV_dev:
    resource: "@gospelcenterMediaBundle/Resources/config/routing.yml"
    prefix:   /tv

gospelcenterAdmin_dev:
    resource: "@gospelcenterAdminBundle/Resources/config/routing.yml"
    prefix:   /{center}/admin
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterEvents_dev:
    resource: "@gospelcenterEventBundle/Resources/config/routing.yml"
    prefix:   /{center}/events
    requirements:
        center: lausanne|annecy|montreux|jura
        
gospelcenterAgenda_dev:
    resource: "@gospelcenterEventBundle/Resources/config/routingAgenda.yml"
    prefix:   /{center}/agenda
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterCelebrations_dev:
    resource: "@gospelcenterCelebrationBundle/Resources/config/routing.yml"
    prefix:   /{center}/celebrations
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterPage_dev:
    resource: "@gospelcenterPageBundle/Resources/config/routing.yml"
    prefix:   /{center}/
    requirements:
        center: lausanne|annecy|montreux|jura

gospelcenterPageGlobal_dev:
    resource: "@gospelcenterPageBundle/Resources/config/routingGlobal.yml"
    prefix:   /