<?php

namespace gospelcenter\ImageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('i');
    
        $qb->leftJoin('i.celebrations', 'cel');
        $qb->leftJoin('cel.center', 'c1');
        
        $qb->leftJoin('i.persons', 'p1');
        $qb->leftJoin('p1.member', 'm');
        $qb->leftJoin('m.centers', 'c2');
        
        $qb->leftJoin('i.slides', 's');
        $qb->leftJoin('s.page', 'p2');
        $qb->leftJoin('p2.center', 'c3');
        
        $qb->leftJoin('i.eventsPicture', 'e1');
        $qb->leftJoin('e1.centers', 'c4');
        
        $qb->leftJoin('i.eventsCover', 'e2');
        $qb->leftJoin('e2.centers', 'c5');
        
        $qb->where('c1.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orWhere('c2.ref = :center')
            ->setParameter('center', $center->getRef());
        
        $qb->orWhere('c3.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orWhere('c4.ref = :center')
            ->setParameter('center', $center->getRef());
        
        $qb->orWhere('c5.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->addOrderBy('i.modifiedDate', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}
