<?php

namespace gospelcenter\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findUpcoming(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('e');
        
        $qb->join('e.centers', 'c')
            ->addSelect('c');
        $qb->join('e.picture', 'p')
            ->addSelect('p');
        
        $qb->where('e.status = :status')
            ->setParameter('status', '1');
        
        $qb->andWhere('c.ref = :center')
            ->setParameter('center', $center->getRef());
          
        $qb = $this->nextEvents($qb);
        
        $qb->orderBy('e.startingDate', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center, $nb, $start)
    {
        $qb = $this->createQueryBuilder('e');
        
        $qb->join('e.centers', 'c')
            ->addSelect('c');
        
        $qb->leftJoin('e.location', 'l')
            ->addSelect('l');
        
        $qb->join('e.picture', 'pic')
            ->addSelect('pic');
            
        $qb->join('e.cover', 'cov')
            ->addSelect('cov');
        
        $qb->where('e.status = :status')
            ->setParameter('status', '1');
            
        $qb->andWhere('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orderBy('e.startingDate', 'DESC');
        
        if($nb > 0)
        {
            $qb->setMaxResults($nb);
        }
        
        $qb->setFirstResult($start);
            
        return $qb->getQuery()->getResult();
        
    }
    
    public function findAllByCenterWithHidden(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('e');
        
        $qb->join('e.centers', 'c')
            ->addSelect('c');
        
        $qb->leftJoin('e.location', 'l')
            ->addSelect('l');
        
        $qb->join('e.picture', 'pic')
            ->addSelect('pic');
            
        $qb->join('e.cover', 'cov')
            ->addSelect('cov');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->orderBy('e.startingDate', 'DESC');
            
        return $qb->getQuery()->getResult();
        
    }
    
    public function findWithAll(\gospelcenter\EventBundle\Entity\Event $event, \gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('e');
        
        $qb->join('e.centers', 'c')
            ->addSelect('c');
        
        $qb->leftJoin('e.location', 'l')
            ->addSelect('l');
        
        $qb->join('e.picture', 'pic')
            ->addSelect('pic');
            
        $qb->join('e.cover', 'cov')
            ->addSelect('cov');
        
        $qb->where('e.id = :id')
            ->setParameter('id', $event->getId());
            
        $qb->andWhere('c.ref = :center')
            ->setParameter('center', $center->getRef());
        
        return $qb->getQuery()->getSingleResult();
    }
    
    public function nextEvents(\Doctrine\ORM\QueryBuilder $qb)
    {
        $qb->andWhere('e.startingDate > :now')
            ->setParameter('now', new \Datetime());
        
        return $qb;
    }
    
}
