<?php

namespace gospelcenter\DateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateRepository extends EntityRepository
{

    public function findNext(\gospelcenter\CenterBundle\Entity\Center $center)
    {

        $query = $this->getEntityManager()
            ->createQuery('
                SELECT d
                FROM gospelcenterDateBundle:Date d
                LEFT JOIN d.celebration cel
                LEFT JOIN cel.center c1
                LEFT JOIN d.event e
                LEFT JOIN e.centers c2
                WHERE ( (c1.ref = :center AND cel.status = 1) OR (c2.ref = :center AND e.status = 1))
                AND d.end >= :now
                ORDER BY d.start ASC'
            )->setParameters(array(
                'center' => $center->getRef(),
                'now' => new \Datetime(),
            ));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findNextEventByCategory(\gospelcenter\CenterBundle\Entity\Center $center, $category)
    {

        $query = $this->getEntityManager()
            ->createQuery('
                SELECT d
                FROM gospelcenterDateBundle:Date d
                LEFT JOIN d.event e
                LEFT JOIN e.centers c
                WHERE c.ref = :center AND e.status = 1 AND e.category = :category
                AND d.end >= :now
                ORDER BY d.start ASC'
            )->setParameters(array(
                'center' => $center->getRef(),
                'now' => new \Datetime(),
                'category' => $category
            ));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
