imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@gospelcenterUserBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    cache:            false
    form:
        resources:
            - 'gospelcenterPeopleBundle:Form:tel.html.twig'
            - '::errors.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: 'twig.extension' } 
            
mobile_detect:
    redirect:
        mobile:
            is_enabled: true            # default false
            host: http://m.gospelcenter.local   # with scheme (http|https), default null, url validate
            status_code: 301            # default 302
            action: no_redirect            # redirect, no_redirect, redirect_without_path
        tablet: 
            is_enabled: false
            action: no_redirect 
        detect_tablet_as_mobile: false   # default false
    switch_device_view: ~
    
    
fos_user:
    db_driver:     orm                        
    firewall_name: main                       
    user_class:    gospelcenter\UserBundle\Entity\User

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: prefix_except_default

liip_imagine:

    resolvers:
        default:
            web_path:
              web_root: %kernel.root_dir%/../web
              cache_prefix: /cache


    loaders:
        default:
            filesystem:
                data_root:  %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          default
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:


        #######################
        ###  thumb_200_200  ###
        #######################
        next_celebration_low:
            quality: 60
            filters:
                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true }

        next_celebration:
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true }

        next_celebration_2x:
            quality: 90
            filters:
                thumbnail: { size: [400, 400], mode: outbound, allow_upscale: true }

        next_celebration_tablet:
            quality: 90
            filters:
                thumbnail: { size: [170, 170], mode: outbound, allow_upscale: true }

        next_celebration_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [340, 340], mode: outbound, allow_upscale: true }

        next_celebration_mobile:
            quality: 90
            filters:
                thumbnail: { size: [90, 90], mode: outbound, allow_upscale: true }

        next_celebration_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [180, 180], mode: outbound, allow_upscale: true }



        ####################
        ###  media_list  ###
        ####################
        media_list_low:
            quality: 60
            filters:
                thumbnail: { size: [300, 169], mode: outbound, allow_upscale: true }

        media_list:
            quality: 90
            filters:
                thumbnail: { size: [300, 169], mode: outbound, allow_upscale: true }

        media_list_2x:
            quality: 90
            filters:
                thumbnail: { size: [600, 338], mode: outbound, allow_upscale: true }

        media_list_tablet:
            quality: 90
            filters:
                thumbnail: { size: [300, 169], mode: outbound, allow_upscale: true }

        media_list_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [600, 338], mode: outbound, allow_upscale: true }

        media_list_mobile:
            quality: 90
            filters:
                thumbnail: { size: [620, 349], mode: outbound, allow_upscale: true }

        media_list_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1240, 698], mode: outbound, allow_upscale: true }



        ##################
        ###  blog_big  ###
        ##################
        blog_big_low:
            quality: 60
            filters:
                thumbnail: { size: [800, 450], mode: outbound, allow_upscale: true }

        blog_big:
            quality: 100
            filters:
                thumbnail: { size: [800, 450], mode: outbound, allow_upscale: true }

        blog_big_2x:
            quality: 90
            filters:
                thumbnail: { size: [1600, 900], mode: outbound, allow_upscale: true }

        blog_big_tablet:
            quality: 100
            filters:
                thumbnail: { size: [800, 450], mode: outbound, allow_upscale: true }

        blog_big_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [800, 450], mode: outbound, allow_upscale: true }

        blog_big_mobile:
            quality: 100
            filters:
                thumbnail: { size: [640, 360], mode: outbound, allow_upscale: true }

        blog_big_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1280, 720], mode: outbound, allow_upscale: true }


        #######################
        ###  event_picture  ###
        #######################
        event_picture_low:
            quality: 60
            filters:
                thumbnail: { size: [260, 136], mode: outbound, allow_upscale: true }

        event_picture:
            quality: 100
            filters:
                thumbnail: { size: [260, 136], mode: outbound, allow_upscale: true }

        event_picture_2x:
            quality: 90
            filters:
                thumbnail: { size: [520, 272], mode: outbound, allow_upscale: true }

        event_picture_tablet:
            quality: 100
            filters:
                thumbnail: { size: [260, 136], mode: outbound, allow_upscale: true }

        event_picture_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [520, 272], mode: outbound, allow_upscale: true }

        event_picture_mobile:
            quality: 100
            filters:
                thumbnail: { size: [620, 349], mode: outbound, allow_upscale: true }

        event_picture_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1240, 698], mode: outbound, allow_upscale: true }


        #####################
        ###  event_cover  ###
        #####################
        event_cover_low:
            quality: 60
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        event_cover:
            quality: 100
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        event_cover_2x:
            quality: 90
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        event_cover_tablet:
            quality: 100
            filters:
                thumbnail: { size: [1024, 232], mode: outbound, allow_upscale: true }

        event_cover_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [2048, 464], mode: outbound, allow_upscale: true }

        event_cover_mobile:
            quality: 100
            filters:
                thumbnail: { size: [640, 145], mode: outbound, allow_upscale: true }

        event_cover_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1280, 290], mode: outbound, allow_upscale: true }



        ##################
        ###  ads_home  ###
        ##################
        ads_home_low:
            quality: 60
            filters:
                thumbnail: { size: [480, 250], mode: outbound, allow_upscale: true }

        ads_home:
            quality: 100
            filters:
                thumbnail: { size: [480, 250], mode: outbound, allow_upscale: true }

        ads_home_2x:
            quality: 90
            filters:
                thumbnail: { size: [960, 500], mode: outbound, allow_upscale: true }

        ads_home_tablet:
            quality: 100
            filters:
                thumbnail: { size: [480, 250], mode: outbound, allow_upscale: true }

        ads_home_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [960, 500], mode: outbound, allow_upscale: true }

        ads_home_mobile:
            quality: 100
            filters:
                thumbnail: { size: [640, 270], mode: outbound, allow_upscale: true }

        ads_home_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1280, 540], mode: outbound, allow_upscale: true }


        ###############
        ###  slide  ###
        ###############
        slide_low:
            quality: 60
            filters:
                thumbnail: { size: [1040, 500], mode: outbound, allow_upscale: true }

        slide:
            quality: 100
            filters:
                thumbnail: { size: [1040, 500], mode: outbound, allow_upscale: true }

        slide_2x:
            quality: 90
            filters:
                thumbnail: { size: [2080, 1000], mode: outbound, allow_upscale: true }

        slide_tablet:
            quality: 100
            filters:
                thumbnail: { size: [1040, 500], mode: outbound, allow_upscale: true }

        slide_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [2080, 1000], mode: outbound, allow_upscale: true }

        slide_mobile:
            quality: 100
            filters:
                thumbnail: { size: [640, 444], mode: outbound, allow_upscale: true }

        slide_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1280, 888], mode: outbound, allow_upscale: true }


        ####################
        ###  media_home  ###
        ####################
        media_home_low:
            quality: 60
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        media_home:
            quality: 100
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        media_home_2x:
            quality: 90
            filters:
                thumbnail: { size: [1700, 384], mode: outbound, allow_upscale: true }

        media_home_tablet:
            quality: 100
            filters:
                thumbnail: { size: [1024, 232], mode: outbound, allow_upscale: true }

        media_home_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [2048, 464], mode: outbound, allow_upscale: true }

        media_home_mobile:
            quality: 100
            filters:
                thumbnail: { size: [640, 145], mode: outbound, allow_upscale: true }

        media_home_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [1280, 290], mode: outbound, allow_upscale: true }


        #################
        ###  tv_wall  ###
        #################
        tv_wall_low:
            quality: 60
            filters:
                thumbnail: { size: [298, 168], mode: outbound, allow_upscale: true }

        tv_wall:
            quality: 100
            filters:
                thumbnail: { size: [298, 168], mode: outbound, allow_upscale: true }

        tv_wall_2x:
            quality: 90
            filters:
                thumbnail: { size: [596, 336], mode: outbound, allow_upscale: true }

        tv_wall_tablet:
            quality: 100
            filters:
                thumbnail: { size: [320, 180], mode: outbound, allow_upscale: true }

        tv_wall_tablet_2x:
            quality: 90
            filters:
                thumbnail: { size: [640, 360], mode: outbound, allow_upscale: true }

        tv_wall_mobile:
            quality: 100
            filters:
                thumbnail: { size: [320, 180], mode: outbound, allow_upscale: true }

        tv_wall_mobile_2x:
            quality: 90
            filters:
                thumbnail: { size: [640, 360], mode: outbound, allow_upscale: true }