security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        gospelcenter\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_LOCAL:         ROLE_USER
        ROLE_LOCAL_ADMIN:   ROLE_LOCAL
        ROLE_MEDIA:         ROLE_LOCAL_ADMIN
        ROLE_CELEBRATION:   ROLE_LOCAL_ADMIN
        ROLE_EVENT:         ROLE_LOCAL_ADMIN
        ROLE_PASTOR:        [ROLE_MEDIA, ROLE_CELEBRATION, ROLE_EVENT]
        ROLE_GLOBAL:        ROLE_USER
        ROLE_SUPER_GLOBAL:  ROLE_GLOBAL
        ROLE_ADMIN:         [ROLE_LOCAL, ROLE_GLOBAL]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_LOCAL' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            #entity: {class: gospelcenter\UserBundle\Entity\User, property: username }
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous:  true
            provider:   main
            form_login:
                success_handler: gc.success_handler
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
                target_path_parameter: continue
                use_referer: true
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:    %secret%

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    

    access_decision_manager:
        # La valeur de « Strategy » peut être : affirmative, unanimous ou consensus
        strategy: unanimous
