parameters:
#    gospelcenter_admin.example.class: gospelcenter\AdminBundle\Example

services:
#    gospelcenter_admin.example:
#        class: %gospelcenter_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
