<?php

namespace gospelcenter\LanguageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{

    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('l');
        
        //$qb->addSelect('COUNT(p.id) AS nbPersons');
        
        $qb->leftJoin('l.persons', 'p');
    
        //$qb->groupBy('l.id');
        
        //$qb->addOrderBy("COUNT(p.id)", 'DESC');
        $qb->addOrderBy("l.ref", 'ASC');
        
        return $qb;
    }
    
}
