<?php

namespace gospelcenter\AccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLevelRepository extends EntityRepository
{
}
