<?php

namespace gospelcenter\CenterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
}
