<?php

namespace gospelcenter\CenterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRepository extends EntityRepository
{

    public function getHomeData(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->addSelect('a');
        $qb->addSelect('i1');

        $qb->addSelect('e');
        $qb->addSelect('d');
        $qb->addSelect('i2');

        $qb->leftJoin('c.ads', 'a');
        $qb->leftJoin('a.image', 'i1');

        $qb->leftJoin('c.events', 'e');
        $qb->leftJoin('e.dates', 'd');
        $qb->leftJoin('e.picture', 'i2');

        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());

        return $qb->getQuery()->getSingleResult();

    }

    public function findAllLocationOfCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->join('c.events', 'e')
            ->addSelect('e');
        
        $qb->join('c.celebrations', 'cel')
            ->addSelect('cel');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->andWhere('e.startingDate > :now')
            ->setParameter('now', new \Datetime());
            
        $qb->andWhere('cel.startingDate > :now')
            ->setParameter('now', new \Datetime());
            
        $qb->addOrderBy('e.startingDate', 'ASC');
        $qb->addOrderBy('cel.startingDate', 'ASC');
            
        return $qb->getQuery()->getSingleResult();
        
    }
    
    public function findNextDates(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->join('c.location', 'l')
            ->addSelect('l');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        return $qb->getQuery()->getResult();
        
    }
    
    public function findAllLocationOfEvents(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->join('c.events', 'e')
            ->addSelect('e');
            
        $qb->join('e.location', 'l')
            ->addSelect('l');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
    public function findAllLocationOfCelebrations(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->join('c.celebrations', 'cel')
            ->addSelect('cel');
            
        $qb->join('cel.location', 'l')
            ->addSelect('l');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
    public function findAllWithMedia()
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->join('c.celebrations', 'cel');
        $qb->leftJoin('cel.video', 'v');
        $qb->leftJoin('cel.audio', 'a');
        
        $qb->addOrderBy('c.name', 'ASC');
            
        return $qb->getQuery()->getResult();
        
    }
    
    
}
