<?php

namespace gospelcenter\CenterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends EntityRepository
{
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('v');
        
        $qb->addSelect('p');
        $qb->addSelect('s');
        $qb->addSelect('m');
        
        $qb->join('v.person', 'p');
        $qb->join('v.centers', 'c');
        
        $qb->leftJoin('p.member', 'm');
        $qb->leftJoin('p.speaker', 's');
        
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb->getQuery()->getResult();
    }

}
