parameters:
#    gospelcenter_article.example.class: gospelcenter\ArticleBundle\Example

services:
#    gospelcenter_article.example:
#        class: %gospelcenter_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
