parameters:
#    gospelcenter_article.example.class: gospelcenter\ArticleBundle\Example

services:
    gospelcenter_article.isexternal:
        class: gospelcenter\ArticleBundle\Twig\Extension\HelperExtension
        tags:
            - { name: twig.extension }
