gospelcenterPage_home:
    path: /
    defaults: { _controller: gospelcenterPageBundle:Page:home }
    
gospelcenterAbout:
    path: /about
    defaults: { _controller: gospelcenterPageBundle:Page:about }
    
gospelcenterLeadership:
    path: /leadership
    defaults: { _controller: gospelcenterPageBundle:Page:leadership }
    
gospelcenterStaff:
    path: /staff
    defaults: { _controller: gospelcenterPageBundle:Page:staff }
    
gospelcenterMusic:
    path: /music
    defaults: { _controller: gospelcenterPageBundle:Page:music }
    
gospelcenterContact:
    path: /contact
    defaults: { _controller: gospelcenterPageBundle:Page:contact }
    requirements:
        _method:  GET

gospelcenterContact_process:
    path: /contact
    defaults: { _controller: gospelcenterPageBundle:Contact:contact }
    requirements:
        _method:  POST

gospelcenterContact_mail:
    path: /contact_mail
    defaults: { _controller: gospelcenterPageBundle:Contact:contactTest }

gospelcenterGive:
    path: /give
    defaults: { _controller: gospelcenterPageBundle:Page:give }

gospelcenterBases_process:
    path: /bases
    defaults: { _controller: gospelcenterPageBundle:Contact:bases }
    requirements:
        _method:  POST

gospelcenterPage_default:
    path: /{page}
    defaults: { _controller: gospelcenterPageBundle:Page:index }
    
