parameters:
#    gospelcenter_celebration.example.class: gospelcenter\CelebrationBundle\Example

services:
    gospelcenter_celebration.celebration_listener:
        class: gospelcenter\CelebrationBundle\Listener\CelebrationListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }