parameters:
#    gospelcenter_image.example.class: gospelcenter\ImageBundle\Example

services:
    gospelcenter_imagine.filter.media_list_filter:
        class: gospelcenter\ImageBundle\Imagine\Filter\Loader\MediaListFilterLoader
        tag:
            - { name: liip_imagine.filter.loader }
            - { loader: media_list_filter }