gospelcenterMedia:
    path:       /
    defaults:   { _controller: gospelcenterMediaBundle:Media:home }
    
gospelcenterMedia_speakers:
    path:       /speakers
    defaults:   { _controller: gospelcenterMediaBundle:Media:speakers }
    
gospelcenterMedia_speaker:
    path:       /speaker/{speaker}
    defaults:   { _controller: gospelcenterMediaBundle:Media:speaker }
    
gospelcenterMedia_video:
    path:       /video/{video}
    defaults:   { _controller: gospelcenterMediaBundle:Media:video }