parameters:
#    gospelcenter_media.example.class: gospelcenter\MediaBundle\Example

services:
#    gospelcenter_media.example:
#        class: %gospelcenter_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
