<?php

namespace Proxies\__CG__\gospelcenter\CenterBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Center extends \gospelcenter\CenterBundle\Entity\Center implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setLocation(\gospelcenter\LocationBundle\Entity\Location $location = NULL)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function setRef($ref)
    {
        $this->__load();
        return parent::setRef($ref);
    }

    public function getRef()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["ref"];
        }
        $this->__load();
        return parent::getRef();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addEvent(\gospelcenter\EventBundle\Entity\Event $events)
    {
        $this->__load();
        return parent::addEvent($events);
    }

    public function removeEvent(\gospelcenter\EventBundle\Entity\Event $events)
    {
        $this->__load();
        return parent::removeEvent($events);
    }

    public function getEvents()
    {
        $this->__load();
        return parent::getEvents();
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function addCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::addCelebration($celebrations);
    }

    public function removeCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::removeCelebration($celebrations);
    }

    public function getCelebrations()
    {
        $this->__load();
        return parent::getCelebrations();
    }

    public function addPage(\gospelcenter\PageBundle\Entity\Page $pages)
    {
        $this->__load();
        return parent::addPage($pages);
    }

    public function removePage(\gospelcenter\PageBundle\Entity\Page $pages)
    {
        $this->__load();
        return parent::removePage($pages);
    }

    public function getPages()
    {
        $this->__load();
        return parent::getPages();
    }

    public function addMember(\gospelcenter\CenterBundle\Entity\Member $members)
    {
        $this->__load();
        return parent::addMember($members);
    }

    public function removeMember(\gospelcenter\CenterBundle\Entity\Member $members)
    {
        $this->__load();
        return parent::removeMember($members);
    }

    public function getMembers()
    {
        $this->__load();
        return parent::getMembers();
    }

    public function addVisitor(\gospelcenter\CenterBundle\Entity\Visitor $visitors)
    {
        $this->__load();
        return parent::addVisitor($visitors);
    }

    public function removeVisitor(\gospelcenter\CenterBundle\Entity\Visitor $visitors)
    {
        $this->__load();
        return parent::removeVisitor($visitors);
    }

    public function getVisitors()
    {
        $this->__load();
        return parent::getVisitors();
    }

    public function addBand(\gospelcenter\CenterBundle\Entity\Band $bands)
    {
        $this->__load();
        return parent::addBand($bands);
    }

    public function removeBand(\gospelcenter\CenterBundle\Entity\Band $bands)
    {
        $this->__load();
        return parent::removeBand($bands);
    }

    public function getBands()
    {
        $this->__load();
        return parent::getBands();
    }

    public function addBase(\gospelcenter\CenterBundle\Entity\Base $bases)
    {
        $this->__load();
        return parent::addBase($bases);
    }

    public function removeBase(\gospelcenter\CenterBundle\Entity\Base $bases)
    {
        $this->__load();
        return parent::removeBase($bases);
    }

    public function getBases()
    {
        $this->__load();
        return parent::getBases();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ref', 'name', 'events', 'location', 'celebrations', 'pages', 'members', 'visitors', 'bands', 'bases');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}