<?php

namespace Proxies\__CG__\gospelcenter\ImageBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Image extends \gospelcenter\ImageBundle\Entity\Image implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function preUpload()
    {
        $this->__load();
        return parent::preUpload();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function preRemoveUpload()
    {
        $this->__load();
        return parent::preRemoveUpload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getUploadDir()
    {
        $this->__load();
        return parent::getUploadDir();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setCreatedDate($createdDate)
    {
        $this->__load();
        return parent::setCreatedDate($createdDate);
    }

    public function getCreatedDate()
    {
        $this->__load();
        return parent::getCreatedDate();
    }

    public function setExtension($extension)
    {
        $this->__load();
        return parent::setExtension($extension);
    }

    public function getExtension()
    {
        $this->__load();
        return parent::getExtension();
    }

    public function setAlt($alt)
    {
        $this->__load();
        return parent::setAlt($alt);
    }

    public function getAlt()
    {
        $this->__load();
        return parent::getAlt();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setOriginalName($originalName)
    {
        $this->__load();
        return parent::setOriginalName($originalName);
    }

    public function getOriginalName()
    {
        $this->__load();
        return parent::getOriginalName();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function addCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::addCelebration($celebrations);
    }

    public function removeCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::removeCelebration($celebrations);
    }

    public function getCelebrations()
    {
        $this->__load();
        return parent::getCelebrations();
    }

    public function addEventsPicture(\gospelcenter\EventBundle\Entity\Event $eventsPicture)
    {
        $this->__load();
        return parent::addEventsPicture($eventsPicture);
    }

    public function removeEventsPicture(\gospelcenter\EventBundle\Entity\Event $eventsPicture)
    {
        $this->__load();
        return parent::removeEventsPicture($eventsPicture);
    }

    public function getEventsPicture()
    {
        $this->__load();
        return parent::getEventsPicture();
    }

    public function addEventsCover(\gospelcenter\EventBundle\Entity\Event $eventsCover)
    {
        $this->__load();
        return parent::addEventsCover($eventsCover);
    }

    public function removeEventsCover(\gospelcenter\EventBundle\Entity\Event $eventsCover)
    {
        $this->__load();
        return parent::removeEventsCover($eventsCover);
    }

    public function getEventsCover()
    {
        $this->__load();
        return parent::getEventsCover();
    }

    public function addPerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::addPerson($persons);
    }

    public function removePerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::removePerson($persons);
    }

    public function getPersons()
    {
        $this->__load();
        return parent::getPersons();
    }

    public function addSlide(\gospelcenter\PageBundle\Entity\Slide $slides)
    {
        $this->__load();
        return parent::addSlide($slides);
    }

    public function removeSlide(\gospelcenter\PageBundle\Entity\Slide $slides)
    {
        $this->__load();
        return parent::removeSlide($slides);
    }

    public function getSlides()
    {
        $this->__load();
        return parent::getSlides();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'createdDate', 'extension', 'alt', 'type', 'originalName', 'description', 'celebrations', 'eventsPicture', 'eventsCover', 'persons', 'slides');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}