<?php

namespace Proxies\__CG__\gospelcenter\LanguageBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Language extends \gospelcenter\LanguageBundle\Entity\Language implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setRef($ref)
    {
        $this->__load();
        return parent::setRef($ref);
    }

    public function getRef()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["ref"];
        }
        $this->__load();
        return parent::getRef();
    }

    public function setValue($value)
    {
        $this->__load();
        return parent::setValue($value);
    }

    public function getValue()
    {
        $this->__load();
        return parent::getValue();
    }

    public function addPerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::addPerson($persons);
    }

    public function removePerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::removePerson($persons);
    }

    public function getPersons()
    {
        $this->__load();
        return parent::getPersons();
    }

    public function addPage(\gospelcenter\PageBundle\Entity\Page $pages)
    {
        $this->__load();
        return parent::addPage($pages);
    }

    public function removePage(\gospelcenter\PageBundle\Entity\Page $pages)
    {
        $this->__load();
        return parent::removePage($pages);
    }

    public function getPages()
    {
        $this->__load();
        return parent::getPages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ref', 'value', 'persons', 'pages');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}