<?php

namespace Proxies\__CG__\gospelcenter\PeopleBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Role extends \gospelcenter\PeopleBundle\Entity\Role implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::addCelebration($celebrations);
    }

    public function removeCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::removeCelebration($celebrations);
    }

    public function getCelebrations()
    {
        $this->__load();
        return parent::getCelebrations();
    }

    public function addBand(\gospelcenter\CenterBundle\Entity\Band $bands)
    {
        $this->__load();
        return parent::addBand($bands);
    }

    public function removeBand(\gospelcenter\CenterBundle\Entity\Band $bands)
    {
        $this->__load();
        return parent::removeBand($bands);
    }

    public function getBands()
    {
        $this->__load();
        return parent::getBands();
    }

    public function addPerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::addPerson($persons);
    }

    public function removePerson(\gospelcenter\PeopleBundle\Entity\Person $persons)
    {
        $this->__load();
        return parent::removePerson($persons);
    }

    public function getPersons()
    {
        $this->__load();
        return parent::getPersons();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'celebrations', 'bands', 'persons');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}