<?php

namespace Proxies\__CG__\gospelcenter\EventBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Event extends \gospelcenter\EventBundle\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPicture(\gospelcenter\ImageBundle\Entity\Image $picture = NULL)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function setCover(\gospelcenter\ImageBundle\Entity\Image $cover = NULL)
    {
        $this->__load();
        return parent::setCover($cover);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setStartingDate($startingDate)
    {
        $this->__load();
        return parent::setStartingDate($startingDate);
    }

    public function getStartingDate()
    {
        $this->__load();
        return parent::getStartingDate();
    }

    public function setEndingDate($endingDate)
    {
        $this->__load();
        return parent::setEndingDate($endingDate);
    }

    public function getEndingDate()
    {
        $this->__load();
        return parent::getEndingDate();
    }

    public function setIntroText($introText)
    {
        $this->__load();
        return parent::setIntroText($introText);
    }

    public function getIntroText()
    {
        $this->__load();
        return parent::getIntroText();
    }

    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setModifiedDate($modifiedDate)
    {
        $this->__load();
        return parent::setModifiedDate($modifiedDate);
    }

    public function getModifiedDate()
    {
        $this->__load();
        return parent::getModifiedDate();
    }

    public function setLocation(\gospelcenter\LocationBundle\Entity\Location $location = NULL)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function getCover()
    {
        $this->__load();
        return parent::getCover();
    }

    public function addCenter(\gospelcenter\CenterBundle\Entity\Center $centers)
    {
        $this->__load();
        return parent::addCenter($centers);
    }

    public function removeCenter(\gospelcenter\CenterBundle\Entity\Center $centers)
    {
        $this->__load();
        return parent::removeCenter($centers);
    }

    public function getCenters()
    {
        $this->__load();
        return parent::getCenters();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'startingDate', 'endingDate', 'introText', 'text', 'status', 'modifiedDate', 'location', 'picture', 'cover', 'centers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}