<?php

namespace Proxies\__CG__\gospelcenter\CelebrationBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Speaker extends \gospelcenter\CelebrationBundle\Entity\Speaker implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getSelect()
    {
        $this->__load();
        return parent::getSelect();
    }

    public function setSpeakerFromDate($speakerFromDate)
    {
        $this->__load();
        return parent::setSpeakerFromDate($speakerFromDate);
    }

    public function getSpeakerFromDate()
    {
        $this->__load();
        return parent::getSpeakerFromDate();
    }

    public function setPerson(\gospelcenter\PeopleBundle\Entity\Person $person)
    {
        $this->__load();
        return parent::setPerson($person);
    }

    public function getPerson()
    {
        $this->__load();
        return parent::getPerson();
    }

    public function addCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::addCelebration($celebrations);
    }

    public function removeCelebration(\gospelcenter\CelebrationBundle\Entity\Celebration $celebrations)
    {
        $this->__load();
        return parent::removeCelebration($celebrations);
    }

    public function getCelebrations()
    {
        $this->__load();
        return parent::getCelebrations();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'speakerFromDate', 'person', 'celebrations');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}