<?php

namespace Proxies\__CG__\gospelcenter\CenterBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Base extends \gospelcenter\CenterBundle\Entity\Base implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setCenter(\gospelcenter\CenterBundle\Entity\Center $center = NULL)
    {
        $this->__load();
        return parent::setCenter($center);
    }

    public function getCenter()
    {
        $this->__load();
        return parent::getCenter();
    }

    public function addParticipant(\gospelcenter\PeopleBundle\Entity\Person $participants)
    {
        $this->__load();
        return parent::addParticipant($participants);
    }

    public function removeParticipant(\gospelcenter\PeopleBundle\Entity\Person $participants)
    {
        $this->__load();
        return parent::removeParticipant($participants);
    }

    public function getParticipants()
    {
        $this->__load();
        return parent::getParticipants();
    }

    public function addOrganizer(\gospelcenter\PeopleBundle\Entity\Person $organizers)
    {
        $this->__load();
        return parent::addOrganizer($organizers);
    }

    public function removeOrganizer(\gospelcenter\PeopleBundle\Entity\Person $organizers)
    {
        $this->__load();
        return parent::removeOrganizer($organizers);
    }

    public function getOrganizers()
    {
        $this->__load();
        return parent::getOrganizers();
    }

    public function setLocation(\gospelcenter\LocationBundle\Entity\Location $location = NULL)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'center', 'participants', 'organizers', 'location');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}