<?php

namespace Proxies\__CG__\gospelcenter\PeopleBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Person extends \gospelcenter\PeopleBundle\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setIsSpeaker($isSpeaker)
    {
        $this->__load();
        return parent::setIsSpeaker($isSpeaker);
    }

    public function getIsSpeaker()
    {
        $this->__load();
        return parent::getIsSpeaker();
    }

    public function setIsMember($isMember)
    {
        $this->__load();
        return parent::setIsMember($isMember);
    }

    public function getIsMember()
    {
        $this->__load();
        return parent::getIsMember();
    }

    public function setIsVisitor($isVisitor)
    {
        $this->__load();
        return parent::setIsVisitor($isVisitor);
    }

    public function getIsVisitor()
    {
        $this->__load();
        return parent::getIsVisitor();
    }

    public function setImage(\gospelcenter\ImageBundle\Entity\Image $image = NULL)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function setLocation(\gospelcenter\LocationBundle\Entity\Location $location = NULL)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setDateOfBirth($dateOfBirth)
    {
        $this->__load();
        return parent::setDateOfBirth($dateOfBirth);
    }

    public function getDateOfBirth()
    {
        $this->__load();
        return parent::getDateOfBirth();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPrivatePhone($privatePhone)
    {
        $this->__load();
        return parent::setPrivatePhone($privatePhone);
    }

    public function getPrivatePhone()
    {
        $this->__load();
        return parent::getPrivatePhone();
    }

    public function setMobilePhone($mobilePhone)
    {
        $this->__load();
        return parent::setMobilePhone($mobilePhone);
    }

    public function getMobilePhone()
    {
        $this->__load();
        return parent::getMobilePhone();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setAbroad($abroad)
    {
        $this->__load();
        return parent::setAbroad($abroad);
    }

    public function getAbroad()
    {
        $this->__load();
        return parent::getAbroad();
    }

    public function setHasChildren($hasChildren)
    {
        $this->__load();
        return parent::setHasChildren($hasChildren);
    }

    public function getHasChildren()
    {
        $this->__load();
        return parent::getHasChildren();
    }

    public function setFunction($function)
    {
        $this->__load();
        return parent::setFunction($function);
    }

    public function getFunction()
    {
        $this->__load();
        return parent::getFunction();
    }

    public function setModifiedDate($modifiedDate)
    {
        $this->__load();
        return parent::setModifiedDate($modifiedDate);
    }

    public function getModifiedDate()
    {
        $this->__load();
        return parent::getModifiedDate();
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function addBandsPopulated(\gospelcenter\CenterBundle\Entity\Band $bandsPopulated)
    {
        $this->__load();
        return parent::addBandsPopulated($bandsPopulated);
    }

    public function removeBandsPopulated(\gospelcenter\CenterBundle\Entity\Band $bandsPopulated)
    {
        $this->__load();
        return parent::removeBandsPopulated($bandsPopulated);
    }

    public function getBandsPopulated()
    {
        $this->__load();
        return parent::getBandsPopulated();
    }

    public function addBandsManaged(\gospelcenter\CenterBundle\Entity\Band $bandsManaged)
    {
        $this->__load();
        return parent::addBandsManaged($bandsManaged);
    }

    public function removeBandsManaged(\gospelcenter\CenterBundle\Entity\Band $bandsManaged)
    {
        $this->__load();
        return parent::removeBandsManaged($bandsManaged);
    }

    public function getBandsManaged()
    {
        $this->__load();
        return parent::getBandsManaged();
    }

    public function setBaseParticipated(\gospelcenter\CenterBundle\Entity\Base $baseParticipated = NULL)
    {
        $this->__load();
        return parent::setBaseParticipated($baseParticipated);
    }

    public function getBaseParticipated()
    {
        $this->__load();
        return parent::getBaseParticipated();
    }

    public function setBaseOrganized(\gospelcenter\CenterBundle\Entity\Base $baseOrganized = NULL)
    {
        $this->__load();
        return parent::setBaseOrganized($baseOrganized);
    }

    public function getBaseOrganized()
    {
        $this->__load();
        return parent::getBaseOrganized();
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function addRole(\gospelcenter\PeopleBundle\Entity\Role $roles)
    {
        $this->__load();
        return parent::addRole($roles);
    }

    public function removeRole(\gospelcenter\PeopleBundle\Entity\Role $roles)
    {
        $this->__load();
        return parent::removeRole($roles);
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function setMember(\gospelcenter\CenterBundle\Entity\Member $member = NULL)
    {
        $this->__load();
        return parent::setMember($member);
    }

    public function getMember()
    {
        $this->__load();
        return parent::getMember();
    }

    public function setSpeaker(\gospelcenter\CelebrationBundle\Entity\Speaker $speaker = NULL)
    {
        $this->__load();
        return parent::setSpeaker($speaker);
    }

    public function getSpeaker()
    {
        $this->__load();
        return parent::getSpeaker();
    }

    public function setVisitor(\gospelcenter\CenterBundle\Entity\Visitor $visitor = NULL)
    {
        $this->__load();
        return parent::setVisitor($visitor);
    }

    public function getVisitor()
    {
        $this->__load();
        return parent::getVisitor();
    }

    public function addLanguage(\gospelcenter\LanguageBundle\Entity\Language $languages)
    {
        $this->__load();
        return parent::addLanguage($languages);
    }

    public function removeLanguage(\gospelcenter\LanguageBundle\Entity\Language $languages)
    {
        $this->__load();
        return parent::removeLanguage($languages);
    }

    public function getLanguages()
    {
        $this->__load();
        return parent::getLanguages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstname', 'lastname', 'title', 'dateOfBirth', 'email', 'privatePhone', 'mobilePhone', 'notes', 'abroad', 'hasChildren', 'function', 'modifiedDate', 'image', 'bandsPopulated', 'bandsManaged', 'baseParticipated', 'baseOrganized', 'location', 'roles', 'member', 'speaker', 'visitor', 'languages');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}