<?php

namespace Proxies\__CG__\gospelcenter\CelebrationBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Celebration extends \gospelcenter\CelebrationBundle\Entity\Celebration implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setExistingSpeakers($existingSpeakers)
    {
        $this->__load();
        return parent::setExistingSpeakers($existingSpeakers);
    }

    public function getExistingSpeakers()
    {
        $this->__load();
        return parent::getExistingSpeakers();
    }

    public function setNewSpeakers($newSpeakers)
    {
        $this->__load();
        return parent::setNewSpeakers($newSpeakers);
    }

    public function getNewSpeakers()
    {
        $this->__load();
        return parent::getNewSpeakers();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setStartingTime($startingTime)
    {
        $this->__load();
        return parent::setStartingTime($startingTime);
    }

    public function getStartingTime()
    {
        $this->__load();
        return parent::getStartingTime();
    }

    public function setEndingTime($endingTime)
    {
        $this->__load();
        return parent::setEndingTime($endingTime);
    }

    public function getEndingTime()
    {
        $this->__load();
        return parent::getEndingTime();
    }

    public function preSave()
    {
        $this->__load();
        return parent::preSave();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setStartingDate($startingDate)
    {
        $this->__load();
        return parent::setStartingDate($startingDate);
    }

    public function getStartingDate()
    {
        $this->__load();
        return parent::getStartingDate();
    }

    public function setEndingDate($endingDate)
    {
        $this->__load();
        return parent::setEndingDate($endingDate);
    }

    public function getEndingDate()
    {
        $this->__load();
        return parent::getEndingDate();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setBestOf($bestOf)
    {
        $this->__load();
        return parent::setBestOf($bestOf);
    }

    public function getBestOf()
    {
        $this->__load();
        return parent::getBestOf();
    }

    public function setKidsProgram($kidsProgram)
    {
        $this->__load();
        return parent::setKidsProgram($kidsProgram);
    }

    public function getKidsProgram()
    {
        $this->__load();
        return parent::getKidsProgram();
    }

    public function setModifiedDate($modifiedDate)
    {
        $this->__load();
        return parent::setModifiedDate($modifiedDate);
    }

    public function getModifiedDate()
    {
        $this->__load();
        return parent::getModifiedDate();
    }

    public function setCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $this->__load();
        return parent::setCenter($center);
    }

    public function getCenter()
    {
        $this->__load();
        return parent::getCenter();
    }

    public function setImage(\gospelcenter\ImageBundle\Entity\Image $image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setLocation(\gospelcenter\LocationBundle\Entity\Location $location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function setVideo(\gospelcenter\MediaBundle\Entity\Video $video = NULL)
    {
        $this->__load();
        return parent::setVideo($video);
    }

    public function getVideo()
    {
        $this->__load();
        return parent::getVideo();
    }

    public function setAudio(\gospelcenter\MediaBundle\Entity\Audio $audio = NULL)
    {
        $this->__load();
        return parent::setAudio($audio);
    }

    public function getAudio()
    {
        $this->__load();
        return parent::getAudio();
    }

    public function addTag(\gospelcenter\CelebrationBundle\Entity\Tag $tags)
    {
        $this->__load();
        return parent::addTag($tags);
    }

    public function removeTag(\gospelcenter\CelebrationBundle\Entity\Tag $tags)
    {
        $this->__load();
        return parent::removeTag($tags);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function addSpeaker(\gospelcenter\CelebrationBundle\Entity\Speaker $speakers)
    {
        $this->__load();
        return parent::addSpeaker($speakers);
    }

    public function removeSpeaker(\gospelcenter\CelebrationBundle\Entity\Speaker $speakers)
    {
        $this->__load();
        return parent::removeSpeaker($speakers);
    }

    public function getSpeakers()
    {
        $this->__load();
        return parent::getSpeakers();
    }

    public function addRole(\gospelcenter\PeopleBundle\Entity\Role $roles)
    {
        $this->__load();
        return parent::addRole($roles);
    }

    public function removeRole(\gospelcenter\PeopleBundle\Entity\Role $roles)
    {
        $this->__load();
        return parent::removeRole($roles);
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'startingDate', 'endingDate', 'description', 'status', 'bestOf', 'kidsProgram', 'modifiedDate', 'center', 'image', 'location', 'video', 'audio', 'tags', 'speakers', 'roles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}