parameters:
#    gospelcenter_event.example.class: gospelcenter\EventBundle\Example

services:
#    gospelcenter_event.example:
#        class: %gospelcenter_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    gospelcenter.antispam:
        class: gospelcenter\Antispam\gospelcenterAntispam
