<?php

namespace gospelcenter\CelebrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CelebrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CelebrationRepository extends EntityRepository
{
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('cel');
        
        $qb->addSelect('s');
        $qb->addSelect('p');
        $qb->addSelect('v');
        $qb->addSelect('a');
        $qb->addSelect('m');
        $qb->addSelect('vi');
        
        $qb->join('cel.center', 'c');
        $qb->leftJoin('cel.speakers', 's');
        $qb->leftJoin('s.person', 'p');
        $qb->leftJoin('p.member', 'm');
        $qb->leftJoin('p.visitor', 'vi');
        $qb->leftJoin('cel.video', 'v');
        $qb->leftJoin('cel.audio', 'a');
            
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
        
        $qb->addOrderBy('cel.startingDate', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
}
