<?php

namespace gospelcenter\CelebrationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use gospelcenter\CenterBundle\Entity\Center;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    public function findAllByCenter(Center $center)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT s, p, m, v, l
                FROM gospelcenterCelebrationBundle:Speaker s
                JOIN s.person p
                LEFT JOIN s.celebrations cel
                JOIN cel.center c
                LEFT JOIN p.member m
                LEFT JOIN p.visitor v
                LEFT JOIN p.languages l
                WHERE c.ref = :center OR p.isGlobal = 1 OR p.center = :center
                ORDER BY p.lastname ASC, p.firstname ASC'
            )->setParameters(
                array(
                    'center' => $center->getRef()
                )
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findAllOrder()
    {
        $qb = $this->createQueryBuilder('s');

        $qb->addSelect('p')
            ->addSelect('m')
            ->addSelect('v')
            ->addSelect('l');

        $qb->leftJoin('s.person', 'p');
        $qb->leftJoin('p.member', 'm');
        $qb->leftJoin('p.visitor', 'v');

        $qb->leftJoin('p.languages', 'l');

        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');

        return $qb->getQuery()->getResult();
    }


    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('s');

        $qb->addSelect('p');

        $qb->join('s.person', 'p');

        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');

        return $qb;
    }


    public function findAllJSON()
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT p.id, p.firstname, p.lastname, p.function, i.id AS image_id
                FROM gospelcenterCelebrationBundle:Speaker s
                JOIN s.person p
                LEFT JOIN p.image i
                ORDER BY p.lastname ASC, p.firstname ASC'
            );

        try {
            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findOne($speaker)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->addSelect('p');

        $qb->join('s.person', 'p');

        $qb->where('p.id = :speaker')
            ->setParameter('speaker', $speaker);

        return $qb->getQuery()->getArrayResult();

    }

    public function findAllWithMedia()
    {

        $query = $this->getEntityManager()
            ->createQuery(
                '
                SELECT s, p, cel, v, a, d, i
                FROM gospelcenterCelebrationBundle:Speaker s
                JOIN s.person p
                JOIN s.celebrations cel
                LEFT JOIN cel.video v
                LEFT JOIN cel.audio a
                LEFT JOIN cel.date d
                LEFT JOIN p.image i
                WHERE v.id > 0 OR a.id > 0
                ORDER BY d.start DESC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
