<?php

namespace gospelcenter\CelebrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p');
        
        $qb->join('s.person', 'p');
        $qb->join('s.celebrations', 'cel');
        $qb->join('cel.center', 'c');
        
        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function findAllOrder()
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p');
        
        $qb->join('s.person', 'p');
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p');
        
        $qb->join('s.person', 'p');
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb;
    }
    
    
    public function findAllJSON()
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p.firstname');
        $qb->addSelect('p.lastname');
        $qb->addSelect('p.function');
        
        $qb->join('s.person', 'p');
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb->getQuery()->getArrayResult();
    }
    
    public function findOne($speaker)
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p');
        
        $qb->join('s.person', 'p');
        
        $qb->where('p.id = :speaker')
            ->setParameter('speaker', $speaker);
            
        return $qb->getQuery()->getArrayResult();
        
    }
    
    public function findAllWithVideo()
    {
        $qb = $this->createQueryBuilder('s');
        
        $qb->addSelect('p');
        
        $qb->join('s.person', 'p');
        $qb->join('s.celebrations', 'cel');
        $qb->join('cel.video', 'v');
            
        $qb->addOrderBy('p.lastname', 'ASC')
            ->addOrderBy('p.firstname', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
}
