parameters:
#    gospelcenter_date.example.class: gospelcenter\DateBundle\Example

services:
#    gospelcenter_date.example:
#        class: %gospelcenter_date.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
