parameters:
#    gospelcenter_access.example.class: gospelcenter\AccessBundle\Example

services:
#    gospelcenter_access.example:
#        class: %gospelcenter_access.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
