<?php

namespace gospelcenter\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{

    public function findAllByCenter(\gospelcenter\CenterBundle\Entity\Center $center)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.center', 'c');

        $qb->where('c.ref = :center')
            ->setParameter('center', $center->getRef());

        return $qb->getQuery()->getResult();
    }
}
